### ISSUE TITLE
Unable TO Save File

### ISSUE THREAD

**Issue by isaacthomasriley** [DraqueT/PolyGlot#1305]
"java.lang.exception: Written File does not match file in memory"

Been trying to save this file for a while now, won't let me save it. :(

**Comment by DraqueT** [comment]
This is something that has poppes up in the newer beta versions and I am trying to track it down. Can you think of anything that you have done recently with the language that is atypical? I am scrambling trying to figure out what this comes from and have not managed to see it, myself. 

Thank you for taking the time to file a bug report!

**Comment by TrapinchO** [comment]
Similar issue to #1195

**Comment by TrapinchO** [comment]
Are you using Beta? It was fixed there.

**Comment by rolfmeles** [comment]
> Are you using Beta? It was fixed there.

Yes I use the latest beta. 
But I did another test:
The project files created before the beta come without a file ending in my case. When editing these, PolyGlot creates extra autosave files and then the bug appears.

Wen I edit project files with the .pgd ending, non such file is created and no save error occures.
Seems to be important to save the file as a new polyglot dictionary with the .pgd ending.

**Comment by TrapinchO** [comment]
Can you trying making a (new) minimal file that triggers the error? See issue #1195 for example.

**Comment by rolfmeles** [comment]
Sorry for letting you wait so long!
In the meantime I also uninstalled PolyGlot and really purched all remaining PolyGlot files off my computer and reinstalled the beta.
For me the bug persists. It is independent of the file. I create a file, I save it, I work on it for some time without saving. At some point saving does not work anymore and the error appears.
Then there are some files named "xxTEMPPGTFILExx" in the PolyGlot folder. One of them contains the latest version I worked with but my "real" file is at an old state and cannot be recovered.
I put both files into the zip archive.

[TriggeringFile.zip](https://github.com/DraqueT/PolyGlot/files/13663013/TriggeringFile.zip)
